name: nytaxi

# TODO: Pick a schedule ("daily", "hourly", "weekly", "monthly") or a cron string.
schedule: daily

# TODO: Set the earliest date this pipeline should consider for full refresh backfills.
# Format: YYYY-MM-DD
start_date: "2019-01-01"

# TODO: Configure default connections so assets can omit explicit `connection: ...`.
# Common pattern: `duckdb: duckdb-default` for local dev.
# Docs (connections): https://getbruin.com/docs/bruin/commands/connections
default_connections:
  bigquery: gcp-default

# TODO: Define pipeline variables using JSON Schema and defaults.
# - Variables must have a `default` so assets can render without `--var`.
# - In SQL/YAML assets: reference as `{{ var.my_variable }}`.
# - In Python assets: read JSON from env var `BRUIN_VARS`.
variables:
  # TODO: Define `taxi_types` as an array of strings with a sensible default.
  taxi_types:
    type: array
    items:
      type: string
    default: ["yellow", "green"]
#   other_string_var: (optional) Add your own variable and use it in both Python and SQL assets.
#     type: string
#     default: "my_value"
